project:
  type: website

editor:
  render-on-save: true
    
website:
  title: "AI-Agenter-F2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Modules"
        href: modules/index.qmd
      - text: "Slides"
        href: slides/index.qmd
      - text: "Web Resources"
        href: web/index.qmd

format:
  html:
    theme:
      - zephyr
      - brand
    mainfont: "Source Sans Pro"
    monofont: "Fira Mono"
    css: styles.css
    toc: true

publish:
  exclude:
    - "documentation"



